package il.tsv.test.playersservice.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import lombok.Data;

import java.util.Date;
@DynamoDBTable(tableName = "Players") // This must be the same as in DynamoDB
@Data
public class PlayerAWS {
    @DynamoDBHashKey(attributeName = "player_id")
    @DynamoDBAutoGeneratedKey
    private String playerID;
    @DynamoDBAttribute
    private Integer birthYear;
    private Integer birthMonth;
    private Integer birthDay;
    private String birthCountry;
    private String birthState;
    private String birthCity;
    private Integer deathYear;
    private Integer deathMonth;
    private Integer deathDay;
    private String deathCountry;
    private String deathState;
    private String deathCity;
    private String nameFirst;
    private String nameLast;
    private String nameGiven;
    private Integer weight;
    private Integer height;
    @DynamoDBTypeConvertedEnum //Specifies that the enum should be stored as a string
    @DynamoDBAttribute
    @Enumerated(EnumType.STRING)
    private Side bats;
    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    @Enumerated(EnumType.STRING)
    private Side thrws;
    @DynamoDBTypeConvertedTimestamp    // Specifies that the date should be stored in a DynamoDB-compatible format.
    private Date debut;
    @DynamoDBTypeConvertedTimestamp
    private Date finalGame;
    private String retroID;
    private String bbrefID;
}
